language: c++

os:
  - osx
  - linux

compiler:
  - clang
  - gcc

env:
  - WANT_SHADERS_GL=on ALLEGRO_SDL=on
  - WANT_SHADERS_GL=on ALLEGRO_SDL=off
  - WANT_SHADERS_GL=off ALLEGRO_SDL=off

install:
    - if [ `uname` = "Linux" ]; then
         export DISPLAY=:99.0;
         sh -e /etc/init.d/xvfb start;
         sudo apt-get update;
         sudo apt-get install -y libvorbis-dev libtheora-dev libwebp-dev libphysfs-dev libopusfile-dev libdumb1-dev libflac-dev libpulse-dev libgtk2.0-dev pandoc libcurl4-nss-dev libenet-dev pulseaudio libasound2-dev libopenal-dev libsdl2-dev libegl1-mesa-dev libgles2-mesa-dev;
      elif [ `uname` = "Darwin" ]; then
         brew update && brew install opusfile libvorbis webp freetype flac physfs dumb theora enet sdl2;
      fi

before_script:
  - mkdir build
  - cd build

script:
    - |
      if [ `uname` = "Linux" ]; then
         cmake .. -DCMAKE_BUILD_TYPE=Debug -DWANT_SHADERS_GL=$WANT_SHADERS_GL -DALLEGRO_SDL=$ALLEGRO_SDL -DWANT_CURL_EXAMPLE=on
         make
         . ../tests/grab_bitmap_suites.sh
         find ../tests -name '*.ini' | grep -v 'compressed' | xargs tests/test_driver | tee /tmp/test_out
         grep -q 'failed tests: 0' /tmp/test_out
         sudo make install
         sudo ldconfig
         gcc ../misc/install_test.c -o install_test $(pkg-config --cflags --libs allegro_image-debug-5 allegro_ttf-debug-5 allegro_acodec-debug-5 allegro_dialog-debug-5 allegro_primitives-debug-5 allegro_video-debug-5)
         pulseaudio -D
         ./install_test
      elif [ `uname` = "Darwin" ]; then
         cmake .. -DWANT_SHADERS_GL=$WANT_SHADERS_GL -DALLEGRO_SDL=$ALLEGRO_SDL -G Xcode
         xcodebuild
      fi

notifications:
  irc:
    channels:
      - "irc.freenode.org#allegro-dev"
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: false
